spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/our_journey
spring.datasource.username=postgres

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true